### ISSUE TITLE
Meeting #2

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/devx-community-legacy#2]
**When:** Tuesday the 14th @ 5PM UTC  in the format of a Twitter Space [@gitpod](https://twitter.com/gitpod)

**"Panelists"**
* [Josh Maxwell](https://twitter.com/cctechwiz)
* [Philipp Strube](https://twitter.com/pst418)
* [Cirpo](https://twitter.com/cirpo)

What does a Panelist do? Basically, you'll have your face on the promo image, and be one of the "main" (but not only) folks in the discussion. No big pressure, the idea is for the community to be inclusive and open, so you can just "be yourself". 🙏

Want to be on the "panel", drop a comment below 👇

**Potential discussion agenda items:** 
* What are the challenges of building/making "Developer Experience"?
* Who are the "big names" in DevX? Who are doing DevX really well? Who should we follow / research look at? 
* What are some good books for getting into DevX? 
* Where is the best place to start when learning about DevX?
* What's missing in the Developer Experience community? 
* How do ideas of "Platform" relate to Developer Experience? 
* How do you start/structure a Developer Experience team? 
* How do you measure Developer Experience? 
* How do you prioritise Developer Experience work? 

If you've got thoughts / suggestions on topics, please drop them below! 🙏 

**Todo**
- [x] Pick date - @loujaybee 
- [ ] Finalise "guest list" 
- [ ] Schedule on Twitter - @pawlean

**Comment by pawlean** [comment]
These questions look awesome! Thanks for kicking it off @loujaybee 🎉

**Comment by cirpo** [comment]
more than happy to contribute folks!

**Comment by loujaybee** [comment]
@cirpo you're in!

**Comment by pawlean** [comment]
All set up! https://twitter.com/devxconf/status/1470427466305003528

**Comment by cctechwiz** [comment]
Notes:
- Customer Obsessed → Engineers/Devs are our customers (treat them like customers)
- A good DX leads to many other good things like $
- hooks for immediate feedback when the pain is felt
- Driven by the motivation to improve DevX rather than as a sales pitch
- Sharing knowledge externally is difficult unless it's part of the culture initially
- Need internal sponsorship to get momentum
- Start small and see where it organically grows
- How do we incentivize teams to contribute to the global DevX, how can they be rewarded for their contributions since it's outside their normal roles?
- Sit in the room with your headphones off and listen for what people are complaining about, make an MR to fix that. Do that a few times and you'll be the head of DevX.
- Google SRE book

Community Q&A:
- What kind of support can a business give to a DevX team? (@? needs attribution)
    - Share data about the things you know
    - Less saying No to disruptive changes, more Yes to experimentation
    - Having empathy is key, understand that this affects developers daily

DevX Players:
- Vercel
- Gitpod
- Netlify
- Digital Ocean
- Heroku
- DAZN
- Qualtrics
- Kubestack
- Akita

Areas considered part of DevX:
- CI/CD
- Development Environment (local or shared)
- Self-service (documentation, admin portals, etc.)
- Bootstrapping (zero to prod)
- Communication between devs and teams
- Low-level infrastructure/platform teams
- Incentivizing being on board with DevX (using your 10% time effectively and not letting it get washed out by other work)
- DevOps
- SRE
- Dev Tooling
- Dev Platforms

(posted these in the discord to generate some discussion hopefully)

**Comment by cirpo** [comment]
shall we close this? as the meeting happened?

**Comment by loujaybee** [comment]
Yup! Thanks @cirpo !

**Comment by elviskahoro** [comment]
@pawlean can you post a recording of the talk somewhere? if you enabled recording you should be able to download it from the Twitter data archive of the hosting account.
